// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {config} from '../models';
import {dedup} from '../models';
import {importsvc} from '../models';

export function BackupDB():Promise<Record<string, any>>;

export function BatchDelete(arg1:Array<number>):Promise<Record<string, number>>;

export function BatchMarkSource(arg1:Array<number>):Promise<Record<string, any>>;

export function ClearAll():Promise<boolean>;

export function DeleteDoc(arg1:number):Promise<boolean>;

export function ExportDataZip(arg1:Array<number>):Promise<Record<string, any>>;

export function ExportDocsZip(arg1:Array<number>):Promise<Record<string, any>>;

export function GetAllDocs():Promise<Array<db.Document>>;

export function GetCheckLogs():Promise<Array<db.CheckLog>>;

export function GetConfig():Promise<config.AppConfig>;

export function GetDocParagraphs(arg1:number):Promise<Array<db.Paragraph>>;

export function GetDuplicateParagraphs(arg1:number,arg2:number):Promise<Array<dedup.DiffResult>>;

export function GetParagraphContext(arg1:number,arg2:number,arg3:number):Promise<Array<db.ParaCtx>>;

export function GetPendingDocs():Promise<Array<db.Document>>;

export function GetRepeatRelations(arg1:number):Promise<Array<Record<string, any>>>;

export function GetSourceDocs():Promise<Array<db.Document>>;

export function ImportFiles(arg1:Array<string>):Promise<importsvc.ImportResult>;

export function ImportFolder(arg1:string):Promise<importsvc.ImportResult>;

export function ImportLegacyFiles(arg1:Array<string>):Promise<Array<Record<string, any>>>;

export function ImportLegacyFolder(arg1:string):Promise<Array<Record<string, any>>>;

export function ImportMixed(arg1:Array<string>):Promise<importsvc.ImportResult>;

export function OpenDoc(arg1:string):Promise<Record<string, any>>;

export function OpenFileDialog():Promise<Array<string>>;

export function RebuildNGramIndex():Promise<Record<string, number>>;

export function RestoreDB(arg1:string):Promise<boolean>;

export function SaveConfig(arg1:config.AppConfig):Promise<Record<string, any>>;

export function SaveFileDialog(arg1:string):Promise<string>;
