// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupDB() {
  return window['go']['main']['App']['BackupDB']();
}

export function BatchDelete(arg1) {
  return window['go']['main']['App']['BatchDelete'](arg1);
}

export function BatchMarkSource(arg1) {
  return window['go']['main']['App']['BatchMarkSource'](arg1);
}

export function ClearAll() {
  return window['go']['main']['App']['ClearAll']();
}

export function DeleteDoc(arg1) {
  return window['go']['main']['App']['DeleteDoc'](arg1);
}

export function ExportDataZip(arg1) {
  return window['go']['main']['App']['ExportDataZip'](arg1);
}

export function ExportDocsZip(arg1) {
  return window['go']['main']['App']['ExportDocsZip'](arg1);
}

export function GetAllDocs() {
  return window['go']['main']['App']['GetAllDocs']();
}

export function GetCheckLogs() {
  return window['go']['main']['App']['GetCheckLogs']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDocParagraphs(arg1) {
  return window['go']['main']['App']['GetDocParagraphs'](arg1);
}

export function GetDuplicateParagraphs(arg1, arg2) {
  return window['go']['main']['App']['GetDuplicateParagraphs'](arg1, arg2);
}

export function GetParagraphContext(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetParagraphContext'](arg1, arg2, arg3);
}

export function GetPendingDocs() {
  return window['go']['main']['App']['GetPendingDocs']();
}

export function GetRepeatRelations(arg1) {
  return window['go']['main']['App']['GetRepeatRelations'](arg1);
}

export function GetSourceDocs() {
  return window['go']['main']['App']['GetSourceDocs']();
}

export function ImportFiles(arg1) {
  return window['go']['main']['App']['ImportFiles'](arg1);
}

export function ImportFolder(arg1) {
  return window['go']['main']['App']['ImportFolder'](arg1);
}

export function ImportLegacyFiles(arg1) {
  return window['go']['main']['App']['ImportLegacyFiles'](arg1);
}

export function ImportLegacyFolder(arg1) {
  return window['go']['main']['App']['ImportLegacyFolder'](arg1);
}

export function ImportMixed(arg1) {
  return window['go']['main']['App']['ImportMixed'](arg1);
}

export function OpenDoc(arg1) {
  return window['go']['main']['App']['OpenDoc'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function RebuildNGramIndex() {
  return window['go']['main']['App']['RebuildNGramIndex']();
}

export function RestoreDB(arg1) {
  return window['go']['main']['App']['RestoreDB'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}
